name: Auto Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update README
      run: |
        # Check for new Markdown files in the 'websites' folder
        NEW_RESOURCES=$(git diff --name-only HEAD~1 | grep '^websites/' | grep '.md$')
        
        # If there are new files, update README.md
        if [ -n "$NEW_RESOURCES" ]; then
          echo "Updating README.md with new resources..."
          python update_readme.py
        else
          echo "No new resources to add to README.md."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
