# pls donot change this
name: Auto Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update README
      run: |
        python scripts/update_readme.py  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}