name: Update README.md

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key from secrets

      - name: Setup Git configuration
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "action@github.com"

      - name: Modify README.md
        run: |
          echo "Updated on $(date)" >> README.md  # Example modification

      - name: Add changes
        run: |
          git add README.md  # Ensure the right file is added
          git diff --cached --exit-code || (git commit -m "Update README.md" && git push origin main)

      - name: Show Git status
        run: git status
