name: Auto Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update README
      run: |
        NEW_RESOURCES=$(git diff --name-only HEAD origin/main | grep '^websites/.*\.md$')
        
        if [ -n "$NEW_RESOURCES" ]; then
          echo "Updating README.md with new resources..."
          python update_readme.py
        else
          echo "No new resources to add to README.md."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
