name: Update README.md and Run Python Script

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r ./.github/requirements.txt

      - name: Run update_readme.py script
        run: python ./.github/update_readme.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes to README.md
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md with new content"
        if: steps.update-readme.outputs.new-entries != '[]'

      - name: Push changes to remote
        run: git push https://github.com/radyalz/AIArticleScout.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.update-readme.outputs.new-entries != '[]'
