name: Update README.md and Run Python Script

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Run update_readme.py script
        run: python scripts/update_readme.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set new-entries environment variable
        id: set-new-entries
        run: echo "new-entries=${{ steps.run_update_readme.outputs.new-entries }}" >> $GITHUB_ENV
        continue-on-error: true  # In case the script doesn't set the output

      - name: Commit changes to README.md
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md with new content"
        if: env.new-entries == 'true'

      - name: Push changes to remote
        run: git push https://github.com/radyalz/AIArticleScout.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: env.new-entries == 'true'
