name: Auto Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update README
      run: |
        # Get the list of modified .md files under 'websites/'
        NEW_RESOURCES=$(git diff --name-only HEAD origin/main | Select-String '^websites/.*\.md$')

        if ($NEW_RESOURCES) {
          echo "Updating README.md with new resources..."
          python update_readme.py
        } else {
          echo "No new resources to add to README.md."
        }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
